package properProject;

public class Instructions {
    public String toString(){

        String words = ("*==================================================* \n \n " +
                        "Hello! Welcome to our game of Mastermind \n" +
        ("\n") +
        ("*==================================================* \n") +
        ("\n") +
        ("In this game there is a hidden code generated by the computer written using 4 color coded balls \n") +
        ("The balls can be selected via number according to the color scheme\n 0: Red\n 1: Orange\n 2: Yellow\n 3: Green\n 4: Blue\n 5: Green\n 6: Purple \n") +
        ("\n") +
        ("*==================================================* \n") +
        ("\n") +
        ("Your Job is to select 4 balls e.g. 0011 is red red orange orange \n and try to guess the original code based on color and position \n") +
        ("We will give you feedback in the form of white and black balls up to a total of 4 for each ball \n") +
        ("A black ball indicates the position and color of a ball have been guessed correctly \n") +
        ("A white ball indicates the color of a ball has been guessed correctly, but not the position \n") +
        ("You have ten tries to get it right before we call it quits \n") +
        ("\n") +
        ("*==================================================* \n") +
        ("\n") +
        ("Lets get it started!"));
        return words;
    }

}

