package properProject;

public class Instructions {
    public static void printInstructions(){

        System.out.println("*==================================================* \n \n " +
                        "Hello! Welcome to our game of Mastermind \n");
        System.out.println("");
        System.out.println("*==================================================*");
        System.out.println("");
        System.out.println("In this game there is a hidden code generated by the computer written using 4 color coded balls");
        System.out.println("The balls can be orange, yellow, red, blue, green and purple");
        System.out.println("");
        System.out.println("*==================================================*");
        System.out.println("");
        System.out.println("Your Job is to select 4 balls and try to guess the original code based on color and position");
        System.out.println("We will give you feedback in form of white and black balls up to a total of 4 for each ball");
        System.out.println("A black ball means you guessed the position and color of a ball correctly");
        System.out.println("A white ball means you only got the color of a ball correctly and not the position");
        System.out.println("You have ten tries to get it right before we call it quits");
        System.out.println("");
        System.out.println("*==================================================*");
        System.out.println("");

        System.out.println("Lets get it started!");

    }
}

