package properProject;

/**
 * Basic instructions for the player
 */

public class Instructions {
    private static ColorManager colorKey = new ColorManager();

    /**
     * Makes a string object with instructions for the player to be displayed on the banner
     * @return words the instructions
     */

    public static String humanManual() {
//
        String words = (
                "Hello! Welcome to our game of Mastermind \n" +
                ("\n") +
                ("\n") +
                ("In this game there is a hidden code generated by the computer written using 4 color coded balls \n") +
                ("The balls can be selected by typing in a string in the console via number according to the color scheme\n 0: Red\n 1: Orange\n 2: Yellow\n 3: Green\n 4: Blue\n 5:Purple \n") +
                ("\n") +
                ("\n") +
                ("Your Job is to select 4 balls (e.g. 0011 is red red orange orange) \nTry to guess the original code based on color and position \n") +
                ("We will give you feedback in the form of white and black balls up to a total of 4 for each ball \n") +
                ("A black ball indicates the position and color of a ball have been guessed correctly \n") +
                ("A white ball indicates the color of a ball has been guessed correctly, but not the position \n") +
                ("You can try 10 times before it quits \n") +
                ("\n") +
                ("\n") +
                ("Or You can ask the computer to play and our algorithm will always solve it in five moves. \n Click your choice below to play in your Java console or let the computer play"));
        return words;
    }

    /**
     * GameManager constructor
     * @param canvas The canvas window to add objects to
     * @param banner the new banner of instructions to display
     * @param board a board object containing the rows in the game
     * @param size the sizes to be used by the board object to make new rows of specific size
     */


    /**
     * Makes a simple feedback string to tell the user that the computer has taken over
     * @return words the feedback
     */

    public String computerManual() {
        String words = ("============================================================================================\n \n" +
                "Please wait while I (your computer) do my awesome thing and solve this puzzle! \n" +
                ("\n") +
                ("============================================================================================"));
        return words;
    }



}

